#if !canImport(ObjectiveC)
import XCTest

extension ConfigArgumentParserExamplesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConfigArgumentParserExamplesTests = [
        ("testAllExamples", testAllExamples),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConfigArgumentParserExamplesTests.__allTests__ConfigArgumentParserExamplesTests),
    ]
}
#endif
