//
//  DefaultConfigFlagSettings.swift
//  ConfigArgumentParser
//
//  Created by Braden Scothern on 9/10/20.
//  Copyright © 2020 Braden Scothern. All rights reserved.
//

@usableFromInline
enum DefaultConfigFlagSettings: ConfigFlagSettings {
    @usableFromInline
    static let configHelp: String = "The config file to use for arguments to execute a subcommand."

    @usableFromInline
    static var dryRunHelp: String = "When set this flag will cause command generated by --\(Self.config) <\(Self.config)> to print rather than run."
}
