name: SwiftPM (Swift 5.5 & Windows)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.5-release
          tag: 5.5-RELEASE

      - uses: actions/checkout@v2
#      - run: swift build
      - run: swift test

