name: SwiftPM (Xcode 12.5 & macOS 11)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    env:
        DEVELOPER_DIR: /Applications/Xcode_12.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
